"""empty message

Revision ID: ec7c421a0f56
Revises: 7c278ce70f7b
Create Date: 2025-01-06 09:40:28.914403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec7c421a0f56'
down_revision = '7c278ce70f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav-characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_character'),
    sa.UniqueConstraint('id_user')
    )
    op.create_table('fav-planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_planet'),
    sa.UniqueConstraint('id_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav-planets')
    op.drop_table('fav-characters')
    # ### end Alembic commands ###
